#!/bin/bash

BASEDIR=$(dirname $0)
TARGET="${BASEDIR}/../../var"

echo "running setup..."
echo "target folder : ${TARGET}"

if [ ! -d "${TARGET}" ]
then
	mkdir $TARGET
fi

sudo bash ${BASEDIR}/redis/setup ${TARGET}

sudo cp ${BASEDIR}/script/* ${TARGET}

echo "setup finished."

