// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;

public class Protocol : ProtocolBase {
	public static  Protocol Instance = new Protocol();
	private Protocol() {
		Protocol.SetProtocol<aoi_add> (aoi_add.Tag);
		Protocol.SetRequest<SprotoType.aoi_add.request> (aoi_add.Tag);
		Protocol.SetResponse<SprotoType.aoi_add.response> (aoi_add.Tag);

		Protocol.SetProtocol<aoi_remove> (aoi_remove.Tag);
		Protocol.SetRequest<SprotoType.aoi_remove.request> (aoi_remove.Tag);

		Protocol.SetProtocol<aoi_update_attribute> (aoi_update_attribute.Tag);
		Protocol.SetRequest<SprotoType.aoi_update_attribute.request> (aoi_update_attribute.Tag);
		Protocol.SetResponse<SprotoType.aoi_update_attribute.response> (aoi_update_attribute.Tag);

		Protocol.SetProtocol<aoi_update_move> (aoi_update_move.Tag);
		Protocol.SetRequest<SprotoType.aoi_update_move.request> (aoi_update_move.Tag);
		Protocol.SetResponse<SprotoType.aoi_update_move.response> (aoi_update_move.Tag);

		Protocol.SetProtocol<aoi_update_move_full> (aoi_update_move_full.Tag);
		Protocol.SetRequest<SprotoType.aoi_update_move_full.request> (aoi_update_move_full.Tag);
		Protocol.SetResponse<SprotoType.aoi_update_move_full.response> (aoi_update_move_full.Tag);

		Protocol.SetProtocol<auth> (auth.Tag);
		Protocol.SetRequest<SprotoType.auth.request> (auth.Tag);
		Protocol.SetResponse<SprotoType.auth.response> (auth.Tag);

		Protocol.SetProtocol<challenge> (challenge.Tag);
		Protocol.SetRequest<SprotoType.challenge.request> (challenge.Tag);
		Protocol.SetResponse<SprotoType.challenge.response> (challenge.Tag);

		Protocol.SetProtocol<character_create> (character_create.Tag);
		Protocol.SetRequest<SprotoType.character_create.request> (character_create.Tag);
		Protocol.SetResponse<SprotoType.character_create.response> (character_create.Tag);

		Protocol.SetProtocol<character_list> (character_list.Tag);
		Protocol.SetResponse<SprotoType.character_list.response> (character_list.Tag);

		Protocol.SetProtocol<character_pick> (character_pick.Tag);
		Protocol.SetRequest<SprotoType.character_pick.request> (character_pick.Tag);
		Protocol.SetResponse<SprotoType.character_pick.response> (character_pick.Tag);

		Protocol.SetProtocol<combat> (combat.Tag);
		Protocol.SetRequest<SprotoType.combat.request> (combat.Tag);
		Protocol.SetResponse<SprotoType.combat.response> (combat.Tag);

		Protocol.SetProtocol<fullmove> (fullmove.Tag);
		Protocol.SetRequest<SprotoType.fullmove.request> (fullmove.Tag);
		Protocol.SetResponse<SprotoType.fullmove.response> (fullmove.Tag);

		Protocol.SetProtocol<handshake> (handshake.Tag);
		Protocol.SetRequest<SprotoType.handshake.request> (handshake.Tag);
		Protocol.SetResponse<SprotoType.handshake.response> (handshake.Tag);

		Protocol.SetProtocol<login> (login.Tag);
		Protocol.SetRequest<SprotoType.login.request> (login.Tag);

		Protocol.SetProtocol<map_ready> (map_ready.Tag);

		Protocol.SetProtocol<move> (move.Tag);
		Protocol.SetRequest<SprotoType.move.request> (move.Tag);
		Protocol.SetResponse<SprotoType.move.response> (move.Tag);

		Protocol.SetProtocol<myauth> (myauth.Tag);
		Protocol.SetRequest<SprotoType.myauth.request> (myauth.Tag);
		Protocol.SetResponse<SprotoType.myauth.response> (myauth.Tag);

		Protocol.SetProtocol<syncclientlag> (syncclientlag.Tag);
		Protocol.SetRequest<SprotoType.syncclientlag.request> (syncclientlag.Tag);
		Protocol.SetResponse<SprotoType.syncclientlag.response> (syncclientlag.Tag);

		Protocol.SetProtocol<syncserverlag> (syncserverlag.Tag);
		Protocol.SetRequest<SprotoType.syncserverlag.request> (syncserverlag.Tag);

	}

	public class aoi_add {
		public const int Tag = 2000;
	}

	public class aoi_remove {
		public const int Tag = 2001;
	}

	public class aoi_update_attribute {
		public const int Tag = 2003;
	}

	public class aoi_update_move {
		public const int Tag = 2002;
	}

	public class aoi_update_move_full {
		public const int Tag = 2004;
	}

	public class auth {
		public const int Tag = 2;
	}

	public class challenge {
		public const int Tag = 3;
	}

	public class character_create {
		public const int Tag = 1001;
	}

	public class character_list {
		public const int Tag = 1000;
	}

	public class character_pick {
		public const int Tag = 1002;
	}

	public class combat {
		public const int Tag = 1005;
	}

	public class fullmove {
		public const int Tag = 1006;
	}

	public class handshake {
		public const int Tag = 1;
	}

	public class login {
		public const int Tag = 4;
	}

	public class map_ready {
		public const int Tag = 1003;
	}

	public class move {
		public const int Tag = 1004;
	}

	public class myauth {
		public const int Tag = 5;
	}

	public class syncclientlag {
		public const int Tag = 100;
	}

	public class syncserverlag {
		public const int Tag = 101;
	}

}